frappe:
  image:
    repository: erasmuspham/frappe
    tag: latest

erpnext:
  image:
    repository: erasmuspham/erpnext
    tag: latest

site:
  name: customer-a
  adminPassword: admin123
  installApps: erpnext

jobs:
  createSite:
    enabled: true
    siteName: customer-a
    adminPassword: admin123
    installApps: erpnext

imagePullSecrets:
  - name: regcred

persistence:
  worker:
    enabled: true
nginx:
  enabled: true
