frappe:
  image:
    repository: erasmuspham/frappe
    tag: {{TAG}}

erpnext:
  image:
    repository: erasmuspham/erpnext
    tag: {{TAG}}

site:
  name: {{CUSTOMER}}
  installApps: erpnext

jobs:
  createSite:
    enabled: true
    siteName: {{CUSTOMER}}
    installApps: erpnext

imagePullSecrets:
  - name: regcred

persistence:
  worker:
    enabled: true
  nginx:
    enabled: true