name: Manual Deploy ERPNext Site

on:
  workflow_dispatch:
    inputs:
      site_file:
        description: "Tên file cấu hình trong folder sites/ (VD: customer1.yaml)"
        required: true
        default: customer1.yaml

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout deploy-infra
        uses: actions/checkout@v3

      - name: Triển khai site ERPNext
        run: |
          SITE_FILE="${{ github.event.inputs.site_file }}"
          SITE_NAME=$(basename "$SITE_FILE" .yaml)

          echo "Deploying: $SITE_NAME"

          helm upgrade --install "$SITE_NAME" ./erpnext \
            -n "$SITE_NAME" --create-namespace \
            -f "sites/$SITE_FILE"

      - name: Kiểm tra pod sau deploy
        run: |
          SITE_FILE="${{ github.event.inputs.site_file }}"
          SITE_NAME=$(basename "$SITE_FILE" .yaml)

          kubectl get pods -n "$SITE_NAME"
          kubectl get svc -n "$SITE_NAME"
