name: Deploy ERPNext Tenant (Only)

on:
  workflow_dispatch:
    inputs:
      customer:
        description: "Tên khách hàng (e.g. customer-a)"
        required: true
      tag:
        description: "Tag image đã build sẵn"
        required: true
      admin_password:
        description: "Mật khẩu admin site"
        required: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} # Nếu repo là private, nên khai báo GH_TOKEN riêng

      - name: Generate values.yaml
        run: |
          chmod +x scripts/generate-values.sh
          ./scripts/generate-values.sh ${{ github.event.inputs.customer }} ${{ github.event.inputs.tag }} ${{ github.event.inputs.admin_password }}

      - name: Commit & Push values.yaml
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@yourdomain.com"
          git add tenants/${{ github.event.inputs.customer }}/values.yaml
          git commit -m "Deploy ${{ github.event.inputs.customer }} with tag ${{ github.event.inputs.tag }}"
          git push